### ISSUE TITLE
AR VIEW DEMO和FACE VIEW DEMO怎么是黑屏的

### ISSUE THREAD

**Issue by qwasnm789** [HMS-Core/hms-scene-demo#1]
我的平板是华为的matepad EMUI和系统和内核的版本都达到要求了

**Comment by scene-kit** [comment]
您好，ARViewDemo和FaceViewDemo中使用了AR Engine的部分能力，需要在您的设备上安装AR Engine Service。请查看您的设备上是否已经安装AR Engine Service，若未安装，您可在应用市场中搜索安装后再次尝试。
